services:
  db:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: schoolenterprisedb
    volumes:
      - /var/lib/postgresql
    ports:
      - 5433:5432
  manage:
    build: 
      context: manage
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
    depends_on:
      - db
    restart: always
    ports:
      - 3001:3000